include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true
    sort_pub_dependencies: false
    implementation_imports: false
    sort_child_properties_last: false
